// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_practica_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::practica::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::practica
{
    MainWindow::MainWindow() :
        MainWindow(make<practica::implementation::MainWindow>())
    {
    }
}
