// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_practica_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::practica::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::practica
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<practica::implementation::XamlMetaDataProvider>())
    {
    }
}
