// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_practica_0_H
#define WINRT_practica_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::practica
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::practica::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::practica::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::practica::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::practica::MainWindow> = L"practica.MainWindow";
    template <> inline constexpr auto& name_v<winrt::practica::XamlMetaDataProvider> = L"practica.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::practica::IMainWindow> = L"practica.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::practica::IMainWindow>{ 0x99F35F6C,0xBCFB,0x5731,{ 0x95,0x16,0x48,0xA2,0x0D,0xD7,0xFD,0x74 } }; // 99F35F6C-BCFB-5731-9516-48A20DD7FD74
    template <> struct default_interface<winrt::practica::MainWindow>{ using type = winrt::practica::IMainWindow; };
    template <> struct default_interface<winrt::practica::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::practica::IMainWindow>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_practica_IMainWindow
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::practica::IMainWindow>
    {
        template <typename D> using type = consume_practica_IMainWindow<D>;
    };
}
#endif
